# Generated by Django 6.0 on 2025-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_tag_thread_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
