# Generated by Django 6.0 on 2026-01-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('forum', '0008_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='courses.course'),
        ),
    ]
